// X — Masquer par pays : donnees partagees (source unique).
// Chargee AVANT content.js (content script ISOLATED) ET par popup.html.
// Expose window.X_HIDE_BY_COUNTRY = { COUNTRIES, DEFAULT_HIDDEN, ALIASES }.
//
// Les chaines de COUNTRIES.n doivent matcher EXACTEMENT ce que X renvoie dans
// `about_profile.account_based_in` (liste reprise de FilterX, source autoritaire ;
// emojis "troll" des regions remplaces par des globes neutres).
(() => {
  // Regions renvoyees par X (globe neutre), puis pays (drapeau ISO).
  const COUNTRIES = [
    { n: "Africa", f: "🌍" },
    { n: "Australasia", f: "🌏" },
    { n: "Caribbean", f: "🌎" },
    { n: "Central Asia", f: "🌏" },
    { n: "East Asia & Pacific", f: "🌏" },
    { n: "East Asia", f: "🌏" },
    { n: "Eastern Europe (Non-EU)", f: "🌍" },
    { n: "Europe", f: "🇪🇺" },
    { n: "North Africa", f: "🌍" },
    { n: "North America", f: "🌎" },
    { n: "Oceania", f: "🌏" },
    { n: "South America", f: "🌎" },
    { n: "South Asia", f: "🌏" },
    { n: "Southeast Asia", f: "🌏" },
    { n: "West Asia", f: "🌍" },
    { n: "Afghanistan", f: "🇦🇫" },
    { n: "Albania", f: "🇦🇱" },
    { n: "Algeria", f: "🇩🇿" },
    { n: "American Samoa", f: "🇦🇸" },
    { n: "Andorra", f: "🇦🇩" },
    { n: "Angola", f: "🇦🇴" },
    { n: "Anguilla", f: "🇦🇮" },
    { n: "Antarctica", f: "🇦🇶" },
    { n: "Antigua and Barbuda", f: "🇦🇬" },
    { n: "Argentina", f: "🇦🇷" },
    { n: "Armenia", f: "🇦🇲" },
    { n: "Aruba", f: "🇦🇼" },
    { n: "Australia", f: "🇦🇺" },
    { n: "Austria", f: "🇦🇹" },
    { n: "Azerbaijan", f: "🇦🇿" },
    { n: "Bahamas", f: "🇧🇸" },
    { n: "Bahrain", f: "🇧🇭" },
    { n: "Bangladesh", f: "🇧🇩" },
    { n: "Barbados", f: "🇧🇧" },
    { n: "Belarus", f: "🇧🇾" },
    { n: "Belgium", f: "🇧🇪" },
    { n: "Belize", f: "🇧🇿" },
    { n: "Benin", f: "🇧🇯" },
    { n: "Bermuda", f: "🇧🇲" },
    { n: "Bhutan", f: "🇧🇹" },
    { n: "Bolivia", f: "🇧🇴" },
    { n: "Bonaire", f: "🇧🇶" },
    { n: "Bosnia and Herzegovina", f: "🇧🇦" },
    { n: "Botswana", f: "🇧🇼" },
    { n: "Bouvet Island", f: "🇧🇻" },
    { n: "Brazil", f: "🇧🇷" },
    { n: "British Indian Ocean Territory", f: "🇮🇴" },
    { n: "British Virgin Islands", f: "🇻🇬" },
    { n: "Brunei Darussalam", f: "🇧🇳" },
    { n: "Bulgaria", f: "🇧🇬" },
    { n: "Burkina Faso", f: "🇧🇫" },
    { n: "Burundi", f: "🇧🇮" },
    { n: "Cambodia", f: "🇰🇭" },
    { n: "Cameroon", f: "🇨🇲" },
    { n: "Canada", f: "🇨🇦" },
    { n: "Cape Verde", f: "🇨🇻" },
    { n: "Cayman Islands", f: "🇰🇾" },
    { n: "Central African Republic", f: "🇨🇫" },
    { n: "Chad", f: "🇹🇩" },
    { n: "Chile", f: "🇨🇱" },
    { n: "China", f: "🇨🇳" },
    { n: "Christmas Island", f: "🇨🇽" },
    { n: "Cocos (Keeling) Islands", f: "🇨🇨" },
    { n: "Colombia", f: "🇨🇴" },
    { n: "Comoros", f: "🇰🇲" },
    { n: "Congo", f: "🇨🇬" },
    { n: "Congo, the Democratic Republic of the", f: "🇨🇩" },
    { n: "Cook Islands", f: "🇨🇰" },
    { n: "Costa Rica", f: "🇨🇷" },
    { n: "Croatia", f: "🇭🇷" },
    { n: "Cuba", f: "🇨🇺" },
    { n: "Curaçao", f: "🇨🇼" },
    { n: "Cyprus", f: "🇨🇾" },
    { n: "Czech Republic", f: "🇨🇿" },
    { n: "Côte d'Ivoire", f: "🇨🇮" },
    { n: "Denmark", f: "🇩🇰" },
    { n: "Djibouti", f: "🇩🇯" },
    { n: "Dominica", f: "🇩🇲" },
    { n: "Dominican Republic", f: "🇩🇴" },
    { n: "Ecuador", f: "🇪🇨" },
    { n: "Egypt", f: "🇪🇬" },
    { n: "El Salvador", f: "🇸🇻" },
    { n: "Equatorial Guinea", f: "🇬🇶" },
    { n: "Eritrea", f: "🇪🇷" },
    { n: "Estonia", f: "🇪🇪" },
    { n: "Ethiopia", f: "🇪🇹" },
    { n: "Falkland Islands (Malvinas)", f: "🇫🇰" },
    { n: "Faroe Islands", f: "🇫🇴" },
    { n: "Fiji", f: "🇫🇯" },
    { n: "Finland", f: "🇫🇮" },
    { n: "France", f: "🇫🇷" },
    { n: "French Guiana", f: "🇬🇫" },
    { n: "French Polynesia", f: "🇵🇫" },
    { n: "French Southern Territories", f: "🇹🇫" },
    { n: "Gabon", f: "🇬🇦" },
    { n: "Gambia", f: "🇬🇲" },
    { n: "Georgia", f: "🇬🇪" },
    { n: "Germany", f: "🇩🇪" },
    { n: "Ghana", f: "🇬🇭" },
    { n: "Gibraltar", f: "🇬🇮" },
    { n: "Greece", f: "🇬🇷" },
    { n: "Greenland", f: "🇬🇱" },
    { n: "Grenada", f: "🇬🇩" },
    { n: "Guadeloupe", f: "🇬🇵" },
    { n: "Guam", f: "🇬🇺" },
    { n: "Guatemala", f: "🇬🇹" },
    { n: "Guernsey", f: "🇬🇬" },
    { n: "Guinea", f: "🇬🇳" },
    { n: "Guinea-Bissau", f: "🇬🇼" },
    { n: "Guyana", f: "🇬🇾" },
    { n: "Haiti", f: "🇭🇹" },
    { n: "Heard Island and McDonald Islands", f: "🇭🇲" },
    { n: "Holy See (Vatican City State)", f: "🇻🇦" },
    { n: "Honduras", f: "🇭🇳" },
    { n: "Hong Kong", f: "🇭🇰" },
    { n: "Hungary", f: "🇭🇺" },
    { n: "Iceland", f: "🇮🇸" },
    { n: "India", f: "🇮🇳" },
    { n: "Indonesia", f: "🇮🇩" },
    { n: "Iran", f: "🇮🇷" },
    { n: "Iraq", f: "🇮🇶" },
    { n: "Ireland", f: "🇮🇪" },
    { n: "Isle of Man", f: "🇮🇲" },
    { n: "Israel", f: "🇮🇱" },
    { n: "Italy", f: "🇮🇹" },
    { n: "Jamaica", f: "🇯🇲" },
    { n: "Japan", f: "🇯🇵" },
    { n: "Jersey", f: "🇯🇪" },
    { n: "Jordan", f: "🇯🇴" },
    { n: "Kazakhstan", f: "🇰🇿" },
    { n: "Kenya", f: "🇰🇪" },
    { n: "Kiribati", f: "🇰🇮" },
    { n: "Korea", f: "🇰🇷" },
    { n: "Korea, Democratic People's Republic of", f: "🇰🇵" },
    { n: "Kuwait", f: "🇰🇼" },
    { n: "Kyrgyzstan", f: "🇰🇬" },
    { n: "Lao People's Democratic Republic", f: "🇱🇦" },
    { n: "Latvia", f: "🇱🇻" },
    { n: "Lebanon", f: "🇱🇧" },
    { n: "Lesotho", f: "🇱🇸" },
    { n: "Liberia", f: "🇱🇷" },
    { n: "Libya", f: "🇱🇾" },
    { n: "Liechtenstein", f: "🇱🇮" },
    { n: "Lithuania", f: "🇱🇹" },
    { n: "Luxembourg", f: "🇱🇺" },
    { n: "Macao", f: "🇲🇴" },
    { n: "Macedonia", f: "🇲🇰" },
    { n: "Madagascar", f: "🇲🇬" },
    { n: "Malawi", f: "🇲🇼" },
    { n: "Malaysia", f: "🇲🇾" },
    { n: "Maldives", f: "🇲🇻" },
    { n: "Mali", f: "🇲🇱" },
    { n: "Malta", f: "🇲🇹" },
    { n: "Marshall Islands", f: "🇲🇭" },
    { n: "Martinique", f: "🇲🇶" },
    { n: "Mauritania", f: "🇲🇷" },
    { n: "Mauritius", f: "🇲🇺" },
    { n: "Mayotte", f: "🇾🇹" },
    { n: "Mexico", f: "🇲🇽" },
    { n: "Micronesia", f: "🇫🇲" },
    { n: "Moldova", f: "🇲🇩" },
    { n: "Monaco", f: "🇲🇨" },
    { n: "Mongolia", f: "🇲🇳" },
    { n: "Montenegro", f: "🇲🇪" },
    { n: "Montserrat", f: "🇲🇸" },
    { n: "Morocco", f: "🇲🇦" },
    { n: "Mozambique", f: "🇲🇿" },
    { n: "Myanmar", f: "🇲🇲" },
    { n: "Namibia", f: "🇳🇦" },
    { n: "Nauru", f: "🇳🇷" },
    { n: "Nepal", f: "🇳🇵" },
    { n: "Netherlands", f: "🇳🇱" },
    { n: "New Caledonia", f: "🇳🇨" },
    { n: "New Zealand", f: "🇳🇿" },
    { n: "Nicaragua", f: "🇳🇮" },
    { n: "Niger", f: "🇳🇪" },
    { n: "Nigeria", f: "🇳🇬" },
    { n: "Niue", f: "🇳🇺" },
    { n: "Norfolk Island", f: "🇳🇫" },
    { n: "Northern Mariana Islands", f: "🇲🇵" },
    { n: "Norway", f: "🇳🇴" },
    { n: "Oman", f: "🇴🇲" },
    { n: "Pakistan", f: "🇵🇰" },
    { n: "Palau", f: "🇵🇼" },
    { n: "Palestine", f: "🇵🇸" },
    { n: "Panama", f: "🇵🇦" },
    { n: "Papua New Guinea", f: "🇵🇬" },
    { n: "Paraguay", f: "🇵🇾" },
    { n: "Peru", f: "🇵🇪" },
    { n: "Philippines", f: "🇵🇭" },
    { n: "Pitcairn", f: "🇵🇳" },
    { n: "Poland", f: "🇵🇱" },
    { n: "Portugal", f: "🇵🇹" },
    { n: "Puerto Rico", f: "🇵🇷" },
    { n: "Qatar", f: "🇶🇦" },
    { n: "Romania", f: "🇷🇴" },
    { n: "Russian Federation", f: "🇷🇺" },
    { n: "Rwanda", f: "🇷🇼" },
    { n: "Réunion", f: "🇷🇪" },
    { n: "Saint Barthélemy", f: "🇧🇱" },
    { n: "Saint Helena, Ascension and Tristan da Cunha", f: "🇸🇭" },
    { n: "Saint Kitts and Nevis", f: "🇰🇳" },
    { n: "Saint Lucia", f: "🇱🇨" },
    { n: "Saint Martin (French part)", f: "🇲🇫" },
    { n: "Saint Pierre and Miquelon", f: "🇵🇲" },
    { n: "Saint Vincent and the Grenadines", f: "🇻🇨" },
    { n: "Samoa", f: "🇼🇸" },
    { n: "San Marino", f: "🇸🇲" },
    { n: "Sao Tome and Principe", f: "🇸🇹" },
    { n: "Saudi Arabia", f: "🇸🇦" },
    { n: "Senegal", f: "🇸🇳" },
    { n: "Serbia", f: "🇷🇸" },
    { n: "Seychelles", f: "🇸🇨" },
    { n: "Sierra Leone", f: "🇸🇱" },
    { n: "Singapore", f: "🇸🇬" },
    { n: "Sint Maarten (Dutch part)", f: "🇸🇽" },
    { n: "Slovakia", f: "🇸🇰" },
    { n: "Slovenia", f: "🇸🇮" },
    { n: "Solomon Islands", f: "🇸🇧" },
    { n: "Somalia", f: "🇸🇴" },
    { n: "South Africa", f: "🇿🇦" },
    { n: "South Georgia and the South Sandwich Islands", f: "🇬🇸" },
    { n: "South Sudan", f: "🇸🇸" },
    { n: "Spain", f: "🇪🇸" },
    { n: "Sri Lanka", f: "🇱🇰" },
    { n: "Sudan", f: "🇸🇩" },
    { n: "Suriname", f: "🇸🇷" },
    { n: "Svalbard and Jan Mayen", f: "🇸🇯" },
    { n: "Swaziland", f: "🇸🇿" },
    { n: "Sweden", f: "🇸🇪" },
    { n: "Switzerland", f: "🇨🇭" },
    { n: "Syrian Arab Republic", f: "🇸🇾" },
    { n: "Taiwan", f: "🇹🇼" },
    { n: "Tajikistan", f: "🇹🇯" },
    { n: "Tanzania", f: "🇹🇿" },
    { n: "Thailand", f: "🇹🇭" },
    { n: "Timor-Leste", f: "🇹🇱" },
    { n: "Togo", f: "🇹🇬" },
    { n: "Tokelau", f: "🇹🇰" },
    { n: "Tonga", f: "🇹🇴" },
    { n: "Trinidad and Tobago", f: "🇹🇹" },
    { n: "Tunisia", f: "🇹🇳" },
    { n: "Turkey", f: "🇹🇷" },
    { n: "Turkmenistan", f: "🇹🇲" },
    { n: "Turks and Caicos Islands", f: "🇹🇨" },
    { n: "Tuvalu", f: "🇹🇻" },
    { n: "US Virgin Islands", f: "🇻🇮" },
    { n: "Uganda", f: "🇺🇬" },
    { n: "Ukraine", f: "🇺🇦" },
    { n: "United Arab Emirates", f: "🇦🇪" },
    { n: "United Kingdom", f: "🇬🇧" },
    { n: "United States", f: "🇺🇸" },
    { n: "United States Minor Outlying Islands", f: "🇺🇲" },
    { n: "Uruguay", f: "🇺🇾" },
    { n: "Uzbekistan", f: "🇺🇿" },
    { n: "Vanuatu", f: "🇻🇺" },
    { n: "Venezuela", f: "🇻🇪" },
    { n: "Viet Nam", f: "🇻🇳" },
    { n: "Wallis and Futuna", f: "🇼🇫" },
    { n: "Western Sahara", f: "🇪🇭" },
    { n: "Yemen", f: "🇾🇪" },
    { n: "Zambia", f: "🇿🇲" },
    { n: "Zimbabwe", f: "🇿🇼" },
    { n: "Åland Islands", f: "🇦🇽" },
  ];

  // Normalisation : X peut renvoyer des variantes. On ramene vers la chaine
  // canonique de COUNTRIES pour que le matching fonctionne.
  const ALIASES = {
    "Türkiye": "Turkey",
    "South Korea": "Korea",
    Czechia: "Czech Republic",
  };

  // Blacklist livree par defaut : les 54 pays d'Afrique + Inde + Pakistan,
  // plus les buckets regionaux correspondants (un compte peut n'etre etiquete
  // qu'au niveau region). L'utilisateur peut tout modifier depuis le popup.
  const DEFAULT_HIDDEN = [
    // Regions
    "Africa",
    "North Africa",
    "South Asia",
    // Afrique
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Congo, the Democratic Republic of the",
    "Côte d'Ivoire",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Swaziland",
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Western Sahara",
    "Zambia",
    "Zimbabwe",
    // Sous-continent indien
    "India",
    "Pakistan",
  ];

  window.X_HIDE_BY_COUNTRY = { COUNTRIES, DEFAULT_HIDDEN, ALIASES };
})();
